### PR TITLE
Add Hindi Translation and README.md Typo Fix

### PR DESCRIPTION
**Pull request by anuragsingh6**

### CODE REVIEW

**Comment by rbtylee** [comment]
Are you interested in more translation work for Bodhi, it would be great to have Hindi Translations for Moksha, our extra modules and more. Send me an email or get in touch with me on Discord if interested. If not interested just comment here if possible,

**Comment by rbtylee** [comment]
Would you mind adding Hindi to the [desktop file](https://github.com/BodhiDev/Desktitle2.0/blob/master/module.desktop.in)?

**Comment by anuragsingh6** [comment]
Yes, I'd like to do Hindi translations for Bodhi.
 
I've updated module.desktop.in. Do I open a new pull?

**Comment by rbtylee** [comment]
Yes this one is already merged. Thanks :)

**Pull request merged**
